DEFAULT_BASE_URL = "https://ilinkai.weixin.qq.com"
DEFAULT_CDN_BASE_URL = "https://novac2c.cdn.weixin.qq.com/c2c"
DEFAULT_BOT_TYPE = "3"
DEFAULT_CHANNEL_VERSION = "monoligh-openclaw"
DEFAULT_API_TIMEOUT_MS = 15_000
DEFAULT_LONG_POLL_TIMEOUT_MS = 30_000
DEFAULT_POLL_INTERVAL_MS = 1_000
DEFAULT_MAX_INBOUND_MEDIA_SIZE_MB = 50
DEFAULT_MERGE_SINGLE_POLL_MESSAGES = True
INBOUND_COLLECTION_QUIET_PERIOD_SECONDS = 5.0
INBOUND_COLLECTION_MAX_WAIT_SECONDS = 15.0

TEXT_ITEM_TYPE = 1
IMAGE_ITEM_TYPE = 2
VOICE_ITEM_TYPE = 3
FILE_ITEM_TYPE = 4
VIDEO_ITEM_TYPE = 5

IMAGE_UPLOAD_TYPE = 1
VIDEO_UPLOAD_TYPE = 2
FILE_UPLOAD_TYPE = 3

IMAGE_EXTENSIONS = {".png", ".jpg", ".jpeg", ".gif", ".webp", ".bmp"}
SKIPPED_MEDIA_PLACEHOLDERS = {
    VOICE_ITEM_TYPE: "[语音]",
    VIDEO_ITEM_TYPE: "[视频]",
}
