DEFAULT_BASE_URL = "https://ilinkai.weixin.qq.com"
DEFAULT_CDN_BASE_URL = "https://novac2c.cdn.weixin.qq.com/c2c"
DEFAULT_BOT_TYPE = "3"
DEFAULT_CHANNEL_VERSION = "monoligh-openclaw"
DEFAULT_API_TIMEOUT_MS = 15_000
DEFAULT_LONG_POLL_TIMEOUT_MS = 30_000
DEFAULT_POLL_INTERVAL_MS = 1_000
DEFAULT_MAX_INBOUND_MEDIA_SIZE_MB = 50
DEFAULT_MERGE_SINGLE_POLL_MESSAGES = True
INBOUND_COLLECTION_QUIET_PERIOD_SECONDS = 5.0
INBOUND_COLLECTION_MAX_WAIT_SECONDS = 15.0

# 容量按 1000 个常规汉字估算，实际发送统一按 3000 UTF-8 字节判断；纯 ASCII 英文约可容纳 3000 字符。
WEIXIN_OPENCLAW_OUTBOUND_TEXT_CHINESE_CHAR_LIMIT = 1_000
WEIXIN_OPENCLAW_OUTBOUND_TEXT_UTF8_BYTE_LIMIT = 3_000
WEIXIN_OPENCLAW_OUTBOUND_TEXT_ASCII_CHAR_LIMIT = 3_000
WEIXIN_OPENCLAW_OUTBOUND_TEXT_MAX_REFINEMENT_ATTEMPTS = 3

TEXT_ITEM_TYPE = 1
IMAGE_ITEM_TYPE = 2
VOICE_ITEM_TYPE = 3
FILE_ITEM_TYPE = 4
VIDEO_ITEM_TYPE = 5

IMAGE_UPLOAD_TYPE = 1
VIDEO_UPLOAD_TYPE = 2
FILE_UPLOAD_TYPE = 3

IMAGE_EXTENSIONS = {".png", ".jpg", ".jpeg", ".gif", ".webp", ".bmp"}
SKIPPED_MEDIA_PLACEHOLDERS = {
    VOICE_ITEM_TYPE: "[语音]",
    VIDEO_ITEM_TYPE: "[视频]",
}
