# 成功类消息 - 通用
MSG_GENERIC_SUCCESS = "MSG_GENERIC_SUCCESS"

# 系统与日志
MSG_LOG_LIST_SUCCESS = "MSG_LOG_LIST_SUCCESS"
MSG_LOG_CLEANER_CLEARED = "MSG_LOG_CLEANER_CLEARED"
ERR_LOG_CLEANER_FAILED = "ERR_LOG_CLEANER_FAILED"

# 成功类消息 - 知识库
MSG_KB_CREATED = "MSG_KB_CREATED"
MSG_KB_UPDATED = "MSG_KB_UPDATED"
MSG_KB_DELETED = "MSG_KB_DELETED"
MSG_KB_DOC_CREATED = "MSG_KB_DOC_CREATED"
MSG_KB_DOC_DELETED = "MSG_KB_DOC_DELETED"

ERR_KB_NOT_FOUND = "ERR_KB_NOT_FOUND"
ERR_KB_COLLECTION_CREATE_FAILED = "ERR_KB_COLLECTION_CREATE_FAILED"
ERR_KB_CREATE_FAILED_WITH_ROLLBACK = "ERR_KB_CREATE_FAILED_WITH_ROLLBACK"
ERR_KB_DELETE_FAILED = "ERR_KB_DELETE_FAILED"
ERR_KB_PROFILE_NOT_FOUND = "ERR_KB_PROFILE_NOT_FOUND"
ERR_KB_DOC_NOT_FOUND = "ERR_KB_DOC_NOT_FOUND"
ERR_KB_DOC_DELETE_FAILED = "ERR_KB_DOC_DELETE_FAILED"
ERR_KB_FILE_EMPTY = "ERR_KB_FILE_EMPTY"
ERR_KB_FILE_ENCODING_ERROR = "ERR_KB_FILE_ENCODING_ERROR"
ERR_KB_VECTOR_WRITE_FAILED = "ERR_KB_VECTOR_WRITE_FAILED"
ERR_KB_DOC_SAVE_FAILED = "ERR_KB_DOC_SAVE_FAILED"
ERR_KB_CHUNK_OVERLAP_ERROR = "ERR_KB_CHUNK_OVERLAP_ERROR"
ERR_KB_DENSE_RETRIEVAL_FAILED = "ERR_KB_DENSE_RETRIEVAL_FAILED"

# 成功类消息 - 用户与认证
MSG_USER_CREATED = "MSG_USER_CREATED"
MSG_USER_UPDATED = "MSG_USER_UPDATED"
MSG_USER_DELETED = "MSG_USER_DELETED"
MSG_USER_LIST_SUCCESS = "MSG_USER_LIST_SUCCESS"
MSG_LOGIN_SUCCESS = "MSG_LOGIN_SUCCESS"

# 成功类消息 - 配置(Profile)
MSG_PROFILE_CREATED = "MSG_PROFILE_CREATED"
MSG_PROFILE_UPDATED = "MSG_PROFILE_UPDATED"
MSG_PROFILE_DELETED = "MSG_PROFILE_DELETED"
MSG_PROFILE_ACTIVATED = "MSG_PROFILE_ACTIVATED"

# 成功类消息 - 提供商(Provider)
MSG_PROVIDER_CREATED = "MSG_PROVIDER_CREATED"
MSG_PROVIDER_UPDATED = "MSG_PROVIDER_UPDATED"
MSG_PROVIDER_DELETED = "MSG_PROVIDER_DELETED"

# 成功类消息 - 提示词(Prompt)
MSG_PROMPT_CREATED = "MSG_PROMPT_CREATED"
MSG_PROMPT_UPDATED = "MSG_PROMPT_UPDATED"
MSG_PROMPT_DELETED = "MSG_PROMPT_DELETED"

# 错误类消息 - 基础
ERR_GENERIC_ERROR = "ERR_GENERIC_ERROR"
ERR_INTERNAL_SERVER_ERROR = "ERR_INTERNAL_SERVER_ERROR"
ERR_DB_OPERATION_FAILED = "ERR_DB_OPERATION_FAILED"
ERR_VALIDATION_FAILED = "ERR_VALIDATION_FAILED"
ERR_PASSWORD_TOO_LONG_BYTES = "ERR_PASSWORD_TOO_LONG_BYTES"
ERR_PROVIDER_BASE_URL_REQUIRED_FOR_RERANK = "ERR_PROVIDER_BASE_URL_REQUIRED_FOR_RERANK"
ERR_PROVIDER_BASE_URL_SCHEME = "ERR_PROVIDER_BASE_URL_SCHEME"
ERR_PROVIDER_MODEL_IDS_ITEM_INVALID = "ERR_PROVIDER_MODEL_IDS_ITEM_INVALID"
ERR_PROVIDER_MODEL_IDS_DUPLICATED = "ERR_PROVIDER_MODEL_IDS_DUPLICATED"

# 成功类消息 - 认证
MSG_ADMIN_RESET_SUCCESS = "MSG_ADMIN_RESET_SUCCESS"

# 错误类消息 - 认证
ERR_ADMIN_PASSWORD_WRONG = "ERR_ADMIN_PASSWORD_WRONG"
ERR_USER_NOT_FOUND_OR_DISABLED = "ERR_USER_NOT_FOUND_OR_DISABLED"
ERR_INVALID_CREDENTIALS = "ERR_INVALID_CREDENTIALS"
ERR_ONLY_ADMIN_ALLOWED = "ERR_ONLY_ADMIN_ALLOWED"
ERR_UNAUTHORIZED = "ERR_UNAUTHORIZED"
ERR_LOGIN_REQUIRED = "ERR_LOGIN_REQUIRED"

# 错误类消息 - 用户业务
ERR_USER_NAME_EXISTS = "ERR_USER_NAME_EXISTS"
ERR_USER_NOT_FOUND = "ERR_USER_NOT_FOUND"

# 错误类消息 - 配置业务
ERR_PROFILE_NOT_FOUND = "ERR_PROFILE_NOT_FOUND"
ERR_PROFILE_NO_EMBEDDING_PROVIDER = "ERR_PROFILE_NO_EMBEDDING_PROVIDER"
ERR_PROFILE_NO_EMBEDDING_MODEL = "ERR_PROFILE_NO_EMBEDDING_MODEL"
ERR_PROFILE_EMBEDDING_PROVIDER_NOT_FOUND = "ERR_PROFILE_EMBEDDING_PROVIDER_NOT_FOUND"
ERR_PROFILE_PROVIDER_NOT_EMBEDDING = "ERR_PROFILE_PROVIDER_NOT_EMBEDDING"
ERR_PROFILE_EMBEDDING_PROVIDER_DISABLED = "ERR_PROFILE_EMBEDDING_PROVIDER_DISABLED"
ERR_PROFILE_EMBEDDING_PROVIDER_NO_URL = "ERR_PROFILE_EMBEDDING_PROVIDER_NO_URL"
ERR_PROFILE_EMBEDDING_CALL_FAILED = "ERR_PROFILE_EMBEDDING_CALL_FAILED"
ERR_PROFILE_RERANK_PROVIDER_NOT_FOUND = "ERR_PROFILE_RERANK_PROVIDER_NOT_FOUND"
ERR_USER_SUPER_PROTECTED = "ERR_USER_SUPER_PROTECTED"
ERR_USER_SUPER_DELETE_FORBIDDEN = "ERR_USER_SUPER_DELETE_FORBIDDEN"
ERR_PROVIDER_RERANK_NO_URL = "ERR_PROVIDER_RERANK_NO_URL"
ERR_PROVIDER_TEST_NO_URL = "ERR_PROVIDER_TEST_NO_URL"
ERR_PROVIDER_TEST_DIMENSION_ERROR = "ERR_PROVIDER_TEST_DIMENSION_ERROR"
ERR_PROVIDER_TEST_FAILED = "ERR_PROVIDER_TEST_FAILED"
ERR_PROFILE_RERANK_CONFIG_INCOMPLETE = "ERR_PROFILE_RERANK_CONFIG_INCOMPLETE"
ERR_PROFILE_RERANK_CANDIDATE_K_TOO_SMALL = "ERR_PROFILE_RERANK_CANDIDATE_K_TOO_SMALL"
ERR_AUTH_RESET_TOKEN_INVALID = "ERR_AUTH_RESET_TOKEN_INVALID"
ERR_PROFILE_PROVIDER_NOT_RERANK = "ERR_PROFILE_PROVIDER_NOT_RERANK"
ERR_PROFILE_RERANK_PROVIDER_DISABLED = "ERR_PROFILE_RERANK_PROVIDER_DISABLED"
ERR_PROFILE_RERANK_PROVIDER_NO_URL = "ERR_PROFILE_RERANK_PROVIDER_NO_URL"
ERR_KB_NOT_FOUND_FOR_QUERY = "ERR_KB_NOT_FOUND_FOR_QUERY"
ERR_KB_NOT_IN_PROFILE = "ERR_KB_NOT_IN_PROFILE"
ERR_PROFILE_NAME_EXISTS = "ERR_PROFILE_NAME_EXISTS"
ERR_ACTIVATE_NO_PROVIDER = "ERR_ACTIVATE_NO_PROVIDER"
ERR_DELETE_LAST_PROFILE = "ERR_DELETE_LAST_PROFILE"
ERR_DELETE_ACTIVE_PROFILE = "ERR_DELETE_ACTIVE_PROFILE"

# 错误类消息 - 提供商业务
MSG_PROVIDER_TEST_SUCCESS = "MSG_PROVIDER_TEST_SUCCESS"
ERR_PROVIDER_NOT_FOUND = "ERR_PROVIDER_NOT_FOUND"
ERR_PROVIDER_NAME_EXISTS = "ERR_PROVIDER_NAME_EXISTS"
ERR_CHAT_PROVIDER_NOT_FOUND = "ERR_CHAT_PROVIDER_NOT_FOUND"
ERR_CHAT_PROVIDER_DISABLED = "ERR_CHAT_PROVIDER_DISABLED"

# 错误类消息 - 提示词业务
ERR_PROMPT_NOT_FOUND = "ERR_PROMPT_NOT_FOUND"
ERR_PROMPT_NAME_EXISTS = "ERR_PROMPT_NAME_EXISTS"


ERR_PROFILE_PROVIDER_MISMATCH = "ERR_PROFILE_PROVIDER_MISMATCH"

# LLM 业务错误
ERR_LLM_CONNECTION_FAILED = "ERR_LLM_CONNECTION_FAILED"
ERR_LLM_API_RESPONSE_ERROR = "ERR_LLM_API_RESPONSE_ERROR"
ERR_LLM_API_RESPONSE_ERROR_WITH_STATUS = "ERR_LLM_API_RESPONSE_ERROR_WITH_STATUS"
ERR_LLM_UNEXPECTED_ERROR = "ERR_LLM_UNEXPECTED_ERROR"
ERR_LLM_UNEXPECTED_ERROR_WITH_DETAIL = "ERR_LLM_UNEXPECTED_ERROR_WITH_DETAIL"

ERR_LLM_PROVIDER_NOT_CONFIGURED = "ERR_LLM_PROVIDER_NOT_CONFIGURED"
ERR_LLM_EMPTY_RESPONSE = "ERR_LLM_EMPTY_RESPONSE"
ERR_LLM_FIRST_CHAR_TIMEOUT = "ERR_LLM_FIRST_CHAR_TIMEOUT"
ERR_RERANK_FORMAT_ERROR = "ERR_RERANK_FORMAT_ERROR"
ERR_EMBEDDING_COUNT_MISMATCH = "ERR_EMBEDDING_COUNT_MISMATCH"
ERR_EMBEDDING_DIMENSION_MISMATCH = "ERR_EMBEDDING_DIMENSION_MISMATCH"

# 验证错误映射（已在 i18n 内部处理，这里置空或废弃）
ERR_MAP = {}
ERR_PROVIDER_EMBEDDING_ONLY = "ERR_PROVIDER_EMBEDDING_ONLY"

# 聊天与会话业务
MSG_SESSION_LIST_SUCCESS = "MSG_SESSION_LIST_SUCCESS"
ERR_SESSION_NOT_FOUND = "ERR_SESSION_NOT_FOUND"
MSG_SESSION_CLEARED = "MSG_SESSION_CLEARED"
ERR_SESSION_NO_PERMISSION = "ERR_SESSION_NO_PERMISSION"
MSG_SESSION_UPDATED = "MSG_SESSION_UPDATED"
MSG_TITLE_GENERATED = "MSG_TITLE_GENERATED"
MSG_MESSAGE_LIST_SUCCESS = "MSG_MESSAGE_LIST_SUCCESS"
ERR_NO_VALID_PROVIDER = "ERR_NO_VALID_PROVIDER"
ERR_CHAT_MESSAGE_OR_ATTACHMENTS_REQUIRED = "ERR_CHAT_MESSAGE_OR_ATTACHMENTS_REQUIRED"
ERR_PROVIDER_EMBEDDING_ONLY_FOR_TITLE = "ERR_PROVIDER_EMBEDDING_ONLY_FOR_TITLE"
ERR_PROVIDER_DISABLED_FOR_TITLE = "ERR_PROVIDER_DISABLED_FOR_TITLE"
MSG_NEW_SESSION = "MSG_NEW_SESSION"
MSG_TITLE_GENERATE_FAILED = "MSG_TITLE_GENERATE_FAILED"
